language: node_js
node_js:
  - "5.5.0"
addons:
    code_climate:
        repo_token: fa271c5456731f9c43b889042522ce2c5785abb69a1c0a127167c241e0840a9d
# script: istanbul cover node_modules/mocha/bin/_mocha -- -R spec
script: node_modules/jest/bin/jest.js --coverage --forceExit
before_script:
  - npm install codeclimate-test-reporter istanbul -g
after_script:
  - codeclimate-test-reporter < ./coverage/lcov.info